listening-port=3478
tls-listening-port=5349
realm=iskenda.com
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=f06bbaa79a3145d7b0817e649d24b9c133c06253724b313ef3c5ba61d5cace31
reuse-addresses
no-cli
no-tlsv1
no-tlsv1_1
no-tlsv1_2
no-stdout-log
log-file=/var/log/turnserver.log
simple-log
